app:
  public-urls:
    - "/api/public/**"
  database:
    postgresql:
      enabled: false
    redis:
      enabled: false

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: sale-server
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration/{vendor}
    enabled: false
  data:
    redis:
      timeout: ${REDIS_TIMEOUT:4000}
      password: ${REDIS_PASSWORD:demo_redis}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
      type: simple

management:
  health:
    redis:
      enabled: false
logging:
  level:
    root: info
    'com.josue.saleserverddd.infrastructure.adapters.outbound.rest.openfeign.UserFeignClient': debug