app:
  public-urls:
    - "/api/public/**"
  database:
    postgresql:
      enabled: false
    redis:
      enabled: false

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: sale-server
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration/{vendor}
    enabled: false
  data:
    redis:
      timeout: ${REDIS_TIMEOUT:4000}
      password: ${REDIS_PASSWORD:demo_redis}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  health:
    redis:
      enabled: false
