app:
  database:
    redis:
      enabled: true

management:
  health:
    redis:
      enabled: true

spring:
  cloud:
    openfeign:
      client:
        config:
          userClient:
            url: http://localhost
            logger-level: full
