openapi: 3.1.0
info:
  title: Demo Sale
  description: |-
    Specification for Demo Sale Application based on OpenAPI 3.1 specification.
  contact:
    email: josue270193@gmail.com
  version: 1.0.0
externalDocs:
  description: Github
  url: https://github.com/josue270193/sale-server
servers:
  - url: http://localhost:8080/api
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    get:
      tags:
        - user
      summary: Get all user registered
      description: Get all user registered
      operationId: getAllUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []
    post:
      tags:
        - user
      summary: Add a new user
      description: Add a new user
      operationId: addUser
      requestBody:
        description: Create a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []

  /user/{userId}:
    get:
      tags:
        - user
      summary: Get user registered by id
      description: Get user registered by id
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: Id of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - demo_auth_jwt: []
    put:
      tags:
        - user
      summary: Edit a user
      description: Edit a user
      operationId: editUser
      parameters:
        - name: userId
          in: path
          description: Id of user to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Modify a registered user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []

components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - lastname
      properties:
        name:
          type: string
        lastname:
          type: string
    UserResponse:
      type: object
      required:
        - id
        - name
        - lastname
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        lastname:
          type: string
    ErrorResponse:
      type: object
      required:
        - type
        - title
        - status
        - detail
        - instance
        - details
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: number
        instance:
          type: string
        details:
          type: array
          items:
            type: object
  securitySchemes:
    demo_auth_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
