openapi: 3.1.0
info:
  title: Sale Server Application
  description: |-
    Specification for Sale Server Application based on OpenAPI 3.1 specification.
  contact:
    email: josue270193@gmail.com
  version: 1.0.0
externalDocs:
  description: Github
  url: https://github.com/josue270193/sale-server
servers:
  - url: http://localhost:8080/api
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    get:
      tags:
        - user
      summary: Retrieve all users registered.
      description: Retrieve all users registered.
      operationId: getAllUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []
    post:
      tags:
        - user
      summary: Create a new user.
      description: Create a new user.
      operationId: addUser
      requestBody:
        description: Parameters for the new user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []

  /user/{userId}:
    get:
      tags:
        - user
      summary: Get an user registered by id.
      description: Get an user registered by id.
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: Id of user to return.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - demo_auth_jwt: []
    put:
      tags:
        - user
      summary: Edit an existence user
      description: Edit an existence user
      operationId: editUser
      parameters:
        - name: userId
          in: path
          description: Id of user to be edited.
          required: true
          schema:
            type: string
      requestBody:
        description: Modify a registered user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserResponse'
      security:
        - demo_auth_jwt: []
    delete:
      tags:
        - user
      summary: Remove an existence user.
      description: Remove an existence user.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: Id of user to return
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful operation
      security:
        - demo_auth_jwt: []
components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - lastname
      properties:
        name:
          type: string
        lastname:
          type: string
    UserResponse:
      type: object
      required:
        - id
        - name
        - lastname
      properties:
        id:
          type: string
        name:
          type: string
        lastname:
          type: string
    ErrorResponse:
      type: object
      required:
        - type
        - title
        - status
        - detail
        - instance
        - details
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: number
        instance:
          type: string
        details:
          type: array
          items:
            type: object
  securitySchemes:
    demo_auth_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
